### ISSUE TITLE
Swapped DAC LVDS PN lines

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Phaser#102]
Two lines for DAC data interface are PN swapped:
![image](https://user-images.githubusercontent.com/9166701/77832976-33d72100-713a-11ea-88bf-7cfe090560ee.png)
![image](https://user-images.githubusercontent.com/9166701/77832985-4baea500-713a-11ea-99c6-5b902d5b95e9.png)

**Comment by jordens** [comment]
There is already a note in the schematic that lists these two and three more LVDS pairs as swapped. IMO this should stay as it is (for compatibility).

**Comment by gkasprow** [comment]
they were swapped on purpose. Routing was much easier.

**Comment by gkasprow** [comment]
closing
