### ISSUE TITLE
ADC Filter Frequencies

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Phaser#103]
The common and differential mode ADC filter bandwidths in the schematics are inaccurate. 

Other filters in the design don't have a frequency annotation. It may be worth checking these have the desired cut-off.

Differential lowpass filter frequencies for the bridge filters used are [given by](https://www.analog.com/media/en/technical-documentation/application-notes/AN-671.pdf): 
![image](https://user-images.githubusercontent.com/14295481/81108329-73024a00-8f10-11ea-83f5-9e2c6f257dbf.png)

The pre-amplification filter has (including the CMC):
*  comon mode: 0.10MHz BW resonance centred on 0.47 MHz -> supression above ~0.6 MHz
*  differntial: 1.0 MHz BW (second pole at 1 GHz) 
![image](https://user-images.githubusercontent.com/14295481/81108016-f8392f00-8f0f-11ea-8ab1-9528acb093e2.png)

The post-amplification filter has:
*  common mode: 3.4 MHz BW
*  differntial: 1.1 MHz BW
![image](https://user-images.githubusercontent.com/14295481/81107842-aee8df80-8f0f-11ea-933d-2f7306df818c.png)

**Comment by gkasprow** [comment]
O, the RCs were changed but annotations were not. Fixed
