### ISSUE TITLE
SMT mmcx connectors

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#106]
I managed to break off the clock input SMT MMCX connectors (as feared in #86) on the first try of removing a connector. That was one of the low insertion/extraction force connectors. While the pads (apart from the center one) were held by the vias, the solder joints broke.
Can we please at least make the clock MMCX connector a through-hole one?

**Comment by gkasprow** [comment]
sure, does it apply to the other designs?

**Comment by jordens** [comment]
No. The others all have through hole mmcx.
I'm also fine ufl for the connectors around the upconverters. They are more experimental and making them through hole may complicate routing.

**Comment by gkasprow** [comment]
we can also glue them, it's an automatic process.

**Comment by gkasprow** [comment]
changing J13, J14, J15, J17 to u.fl
changing J7 to THT one
