### ISSUE TITLE
power budget: OPA2197

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#109]
there are two sets of OPA2197. Both are listed as being supplied from +-11V5 in the power budget, which is not correct

![image](https://user-images.githubusercontent.com/21218399/91584133-1b1da200-e94a-11ea-93b8-f8f4dc287304.png)
![image](https://user-images.githubusercontent.com/21218399/91584153-253fa080-e94a-11ea-927a-f2b126ae28ca.png)
![image](https://user-images.githubusercontent.com/21218399/91584173-2cff4500-e94a-11ea-8ce8-2b8fe7b94013.png)

**Comment by gkasprow** [comment]
good catch, fixed

**Comment by dnadlinger** [comment]
As a minor detail, also seems like those feedback resistors are unnecessary, or at least unnecessarily large, on the reference buffers.

**Comment by gkasprow** [comment]
they match the resistance visible by the positive opamp input

**Comment by dnadlinger** [comment]
But the OPA197 bias current is 20 pA max., so they only serve to increase voltage noise for little benefit?

**Comment by gkasprow** [comment]
in this case, you are right.
