### ISSUE TITLE
clocking notes

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#11]
Copy from Urukul:
- 125MHz from FP SMA, MMCX or on-board XO
- high-quality LVDS fanout to DAC/modulators
- MMCX + solder jumpers to allow using an external LO (for debugging)
- route modulator LO output to MMCX (DNP by default) for debugging
- PLL locked indicators to RED LEDs on FP

**Comment by jordens** [comment]
I'd be happy to drop the xo. And the associated mux in this case. It would require special consideration if the DAC clock is not locked to the link clock.

**Comment by jordens** [comment]
Note that I haven't checked phase determinism with an external DAC clock bypassing the pll.
Also if the dac/lo pll don't have hardware pll lock indicator pins, then routing those signals to fpleds will be tricky.

**Comment by hartytp** [comment]
Ack re ext dac clock. Afaict it’s not needed in any case (if the fpga transceiver pll is good enough for our ref clk l, the dac pll should be fine!)

**Comment by hartytp** [comment]
Still nice to have a way of injecting an ext dac clock during debugging though even if it leads to phase indeterminism

**Comment by gkasprow** [comment]
I kept ext clock, removed oscillator. TRF chip, GTP and DAC PLL are clocked from same clock mux outputs

**Comment by gkasprow** [comment]
lock outptus are routed to FPGA, as well as LEDs

**Comment by hartytp** [comment]
Perfect

**Comment by gkasprow** [comment]
@hartytp the schematic is ready for review
https://github.com/sinara-hw/Phaser/releases/tag/v1.0rc1

**Comment by hartytp** [comment]
Amazing! Thanks

Will review tomorrow
