### ISSUE TITLE
baseband load

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#110]
R37, R39, R40, R54, R61, R67, R76, R86 should be 0R in the baseband variant. See DAC34H8X EVM.

Also check termination resistors at the DAC outputs.

**Comment by hartytp** [comment]
to do: make this change and verify IMD afterwards

**Comment by gkasprow** [comment]
fixed
![obraz](https://user-images.githubusercontent.com/4325054/111031005-a7cf0f80-8405-11eb-8a88-11cf764f3ac8.png)
