### ISSUE TITLE
RAM memory test

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#111]
@gkasprow during your initial testing, did you run a mem test/SI test on the RAM on phaser? It's worth checking this before the next hardware revision.

**Comment by gkasprow** [comment]
no, we didn't do that AFAIR. This can be easily done with Xilinx MIG. It's the same SDRAM as in Kasli, but anyway, it's worth checking with Xilinx tool because it provides in depth diagnostics, eye diagrams etc

**Comment by hartytp** [comment]
:+1:

**Comment by gkasprow** [comment]
the SDRAM works at 400MHz. I'm running the XIlinx test generator with MIG, and cannot trigger it on dgb_cmp_error signal which means this signal does not toggle.
![obraz](https://user-images.githubusercontent.com/4325054/94264907-e21c2180-ff37-11ea-8233-ee695b3da2b7.png)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/94265359-a6ce2280-ff38-11ea-8152-0eb85705dbd9.png)

**Comment by hartytp** [comment]
goood!
