### ISSUE TITLE
Solder Mask and reflow reliability

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#117]
There are about a dozen instances where gaps between pads don't have solder mask or where components are really close together. Especially the decaps under the dac and the inductors (L31 etc) at the upconverters baseband inputs. The parts float around and move during reflow. Under the dac they merge and rotate because there is unmasked copper between parts. The inductors tip over and lean against each other (their placement is probably also bad in terms of coupling). If this isn't clear from the description I'll take a photo.
Let's fix that.

**Comment by gkasprow** [comment]
OK, I know which ones you mean. we need to slightly separate the capacitors
![obraz](https://user-images.githubusercontent.com/4325054/93687882-bcb78f80-fac1-11ea-931f-0ed6796204a2.png)

**Comment by jordens** [comment]
Yes. The tilting of the (blue) inductors (L31, L29, L33, L38) at the upconverter BB inputs can also be seen in your [photo](https://user-images.githubusercontent.com/4325054/75609757-83aad400-5b0b-11ea-8fe7-7b3fab54664c.jpg).
The pads look really small.

**Comment by gkasprow** [comment]
fixed 
![obraz](https://user-images.githubusercontent.com/4325054/110867520-2bcead80-82c7-11eb-8fc5-caf37b5195d4.png)

**Comment by gkasprow** [comment]
I changed the rule to 0.15mm instead of 75um

**Comment by jordens** [comment]
Also the mixer inductors?
![image](https://user-images.githubusercontent.com/1338946/110938898-dd57f800-8334-11eb-957e-a9022e51dd85.png)

**Comment by gkasprow** [comment]
I separated them and increased the pad size
