### ISSUE TITLE
Fix crosstalk

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#118]

**Comment by hartytp** [comment]
This is RF0 out to RF1 out and vice versa, right?

**Comment by jordens** [comment]
Yes

**Comment by jordens** [comment]
Currently there is anywhere between 70 and 30 dB coupling loss between the two channels (at 1.2 GHz) because of the proximity to the panel RF shielding lip. On my board a light touch makes all the difference. Why can't we finally use longer SMA connectors everywhere that bridge the gap between the board and the panel without touching the panel and without having to extend the board while still fitting through the panel? I know that there are longer connectors.

**Comment by gkasprow** [comment]
shall we use Amphenol 132203-16 for the RF path? they are 8mm longer.
Shall we move them by 8mm to keep a consistent connector length above the panel ?

**Comment by gkasprow** [comment]
I found nice fitting connectors from Amp: 132203-14
![obraz](https://user-images.githubusercontent.com/4325054/111040756-e92ae380-8434-11eb-8349-8ba29dde1fd8.png)
