### ISSUE TITLE
DAC output termination resistors far away from DAC

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#120]
Should and can be much closer. Required and stressed multiple times in the datasheets. (The impedance between the DAC output and the resistors does not match the trace dimensions).

**Comment by hartytp** [comment]
Thanks @jordens 

One thing I was curious about here is why we didn't follow the EVM for the DAC outputs.

![image](https://user-images.githubusercontent.com/21218399/94124732-46ae8200-fe4d-11ea-9a7e-e63aa86e2329.png)

![image](https://user-images.githubusercontent.com/21218399/94124780-5a59e880-fe4d-11ea-89e0-4b630bfa5bee.png)

**Comment by jordens** [comment]
This is more for #110 
It depends on the variant and on the impedance at the balun and also the series resistors before the balun.

**Comment by gkasprow** [comment]
Fixed
![obraz](https://user-images.githubusercontent.com/4325054/111031440-de0d8e80-8407-11eb-9bed-bc99665b01df.png)
