### ISSUE TITLE
1:2 Balun does not double the voltage

### ISSUE THREAD

**Issue by Jacky2k** [sinara-hw/Phaser#123]
There is a comment in the schematic (PDF page 10) about the TR5A balun, saying:
`Balun will double that voltage` 
Please correct me if I am wrong, but that is not correct if the termination on the secondary side is 50R.
The 1:2 ratio relates to the impedance, not the voltage. As the power is (roughly) constant, the voltage will increase by sqrt(2), while the current will decrease by sqrt(2), doubling the impedance. But the voltage is only amplified by sqrt(2).

**Comment by gkasprow** [comment]
@hartytp shall we use other balun?

**Comment by hartytp** [comment]
Not unless there is a specific reason to change it (and I'm not aware of anyone raising one). I believe the post above was a comment that the annotation is incorrect rather than a request to change the balun

**Comment by Jacky2k** [comment]
I just noticed that the annotation is wrong. I don't know if a 1:2 voltage transformation was intended.

**Comment by gkasprow** [comment]
ok, right.
