### ISSUE TITLE
Phase noise measurement

### ISSUE THREAD

**Issue by sotirova** [sinara-hw/Phaser#125]
# Setup

- EEM0 of a Kasli 2.0 connected to EEM0 of a phaser baseband board
- Kasli 125 MHz ext ref from CLK SYN of R&S SMA 100A
- Phaser 125 MHz ext ref from RF output of R&S SMA 100A; output level 0 dB
- Generate a single tone from RF0 of phaser at 150 MHz, output level -9.1 dBm
- Connect RF0 of phaser to R&S phase noise analyser

# Measurement results

First look at phase noise when phaser is using its internal clock vs when it is given an external 125 MHz clock as described above. For both of these measurements Kasli was connected to an external 125 MHz reference as above.
![image](https://user-images.githubusercontent.com/30626684/109571413-96bbff80-7ae3-11eb-865f-35981be509e4.png)

For reference, here is also the phase noise from the Kasli MMCX clock outputs when using the Kasli internal clock vs when Kasli takes an external 125 MHz reference.
![image](https://user-images.githubusercontent.com/30626684/109571389-8c016a80-7ae3-11eb-9a6b-9d84ac77cfe2.png)

**Comment by hartytp** [comment]
> Kasli 125 MHz ext ref from CLK SYN of R&S SMA 100A

Interesting. Do you know/did you ever measure what the phase noise spectrum of that output is? I recall it being significantly worse than the main output, but can't find any info in the spec sheet.

**Comment by hartytp** [comment]
Anyway, that's lovely data and generally better than I'd expected. From a physics perspective, that's plenty good enough for everything I want to do, which is great.

In terms of background curiosity/calibrating expectations for what should be doable for this kind of design, the AD9910 noise graphs with and w/o PLL are copied below. My understanding is that DDS chips like the AD9910 are generally about as good as one gets for this kind of digital synthesis so are a pretty good reference.

![image](https://user-images.githubusercontent.com/21218399/109619540-d0672780-7b30-11eb-9330-707bdfbc9aed.png)

Looks like phaser is within 10dB of the AD9910 at all frequencies, a bit better than the 9910 at higher frequencies and a bit worse at lower frequencies, but broadly comparable throught.

![image](https://user-images.githubusercontent.com/21218399/109619666-f7255e00-7b30-11eb-98b4-039f5087a8f6.png)

Phase with PLL is something like 20dB worse than the AD9910 w/o PLL for close-in noise with less than 10dB between them for broader-band noise. 

As a general point of interest, I'd be curious to know what the noise spectrum of phaser looks like without the PLL, but that requires a bit of reconfiguration is is not something we need to worry about.

**Comment by hartytp** [comment]
Anyway, good work @sotirova! I don't see anything suspicious here (the DAC data sheet doesn't have phase noise plots so doesn't give us anything to directly compare with, but I don't see anything in the above to suggest we're doing worse than I'd expect).

**Comment by sotirova** [comment]
Thanks for the comments @hartytp!

> Interesting. Do you know/did you ever measure what the phase noise spectrum of that output is? I recall it being significantly worse than the main output, but can't find any info in the spec sheet.

Here's the phase noise of the synth RF OUT and CLK SYN for reference - indeed the CLK SYN looks worse than the main RF output
![synth](https://user-images.githubusercontent.com/30626684/109636377-6ad06680-7b43-11eb-93f6-5a09a83b25e6.png)

**Comment by hartytp** [comment]
> Here's the phase noise of the synth RF OUT and CLK SYN for reference - indeed the CLK SYN looks worse than the main RF output

What carrier frequency?

**Comment by sotirova** [comment]
> What carrier frequency?
125 MHz both, as used in the setup

**Comment by hartytp** [comment]
anyway, good to know that the CLK SYN phase noise is not a limitation here (although not by that far)

**Comment by pathfinder49** [comment]
I've performed similar measurements for the Phaser-Upconverter variant.

My setup:
* 10 MHz and 125 MHz reference frequencies generated by R&S SMA 100 A
* R&S FSWP phase noise analyser (using 10 MHz external reference)
* Kasli v1.1 (using 125 MHz external reference)
* Phaser upconverter (this uses the kasli clock distribution or dedicated 125 MHz external reference, see below)
* For measuring LO:
    * All amplitudes and frequencies set to zero
* For measuring RF output
    * DAC-NCO at 200 MHz
    * DUC at 130.3 MHz
    * Kasli oscillator at 7 MHz

|   \   |   Using external reference distributed by Kasli   |   Using dedicated phaser reference   |
|   ---   |   ---   |   ---   |
|   Phaser Reference Clock    |   ![Kasli 125MHz](https://user-images.githubusercontent.com/14295481/114720070-97c18d00-9d2f-11eb-95b9-18361603a265.PNG)   |   ![ext ref](https://user-images.githubusercontent.com/14295481/114720109-a1e38b80-9d2f-11eb-9d0b-13033838df65.PNG)   |
|   Phaser 2875 MHz Local Oscillator   |   ![Lo 2875 MHz](https://user-images.githubusercontent.com/14295481/114720236-c3447780-9d2f-11eb-9a49-403adf649aa2.PNG)   |   ![LO 2875 MHz ext clock](https://user-images.githubusercontent.com/14295481/114720266-ca6b8580-9d2f-11eb-8341-593e53b6dab3.PNG)   |
|   Phaser 3.2123 GHz output   |   ![RF 3212-3 MHz with LO 2875 MHz](https://user-images.githubusercontent.com/14295481/114720980-62696f00-9d30-11eb-8e89-884cb3fdafe2.PNG)   |    ![RF 3212-3 MHz with LO 2875 MHz ext clock](https://user-images.githubusercontent.com/14295481/114721023-6c8b6d80-9d30-11eb-8737-0e9b3ce092f6.PNG)   |

At ~3 GHz the output phase noise is dominated by the TRF-LO phase noise. The phase noise can be improved substantially by using a dedicated frequency reference.
