### ISSUE TITLE
advanced fan control

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Phaser#126]
@jordens do you think we should add advanced fan control with TACHO input? I mean the circuit like in the Thermostat EEM
![obraz](https://user-images.githubusercontent.com/4325054/111036786-5a609b80-8421-11eb-9498-2dca69692e4b.png)

**Comment by jordens** [comment]
If reasonably easy, yes. That would be great!

**Comment by gkasprow** [comment]
ok, done
