### ISSUE TITLE
DSP Block Diagram

### ISSUE THREAD

**Issue by RHanley1** [sinara-hw/Phaser#128]
It would be useful if there was a functional block diagram of the DSP to give a nice overview of phaser. There is an old diagram in #1 , however I believe this is not quite up-to-date with the latest release. Does an up-to-date diagram exist?

**Comment by RHanley1** [comment]
This has been posted in Quartiq/phaser (https://github.com/quartiq/phaser/issues/16). Would probably be worthwhile putting a link to the quartiq wiki?

**Comment by jordens** [comment]
Closing as invalid here and addressed elsewhere.
