### ISSUE TITLE
VCC_LOx should be P3V3A not P5V0A

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Phaser#131]
From discussion in #130

**Comment by gkasprow** [comment]
@pkozakiewicz it needs manual fixing after production, before tests.

**Comment by gkasprow** [comment]
fixed 
![obraz](https://user-images.githubusercontent.com/4325054/116069990-595f9280-a68c-11eb-80f8-3e88de25b91a.png)

**Comment by gkasprow** [comment]
fixed in v1.1.1
