### ISSUE TITLE
Fan without tacho

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/Phaser#142]
Fan mentioned in HS1 component - FI23 (https://www.radianheatsinks.com/product/fi23/) does not support tacho wire:

![image](https://user-images.githubusercontent.com/9166701/118470954-7fb2a400-b707-11eb-96f1-01144b2197b7.png)

Additionally HS1 component could be moved to PWR_Supply sheet to be close to the driving circuit.

**Comment by gkasprow** [comment]
I added note on schematic. Tacho is not supported in firmware AFAIK
