### ISSUE TITLE
heat sink DAC and up-converters

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Phaser#144]
DACs and up-converters get very hot as noted [here](https://github.com/sinara-hw/Phaser/issues/101#issuecomment-682044877). We see temperature dependence to carrier feedthrough compensation on up-converters. Things will be more stable with better heat sinking. Keep in mind for next revision.

**Comment by gkasprow** [comment]
You can glue popular [RPI heatsinks](https://www.amazon.pl/Heqishun-radiator%C3%B3w-aluminium-aluminiowe-przewodz%C4%85c%C4%85/dp/B0814V66JV) and see if that helps.
In the next revision, I will think of it.

**Comment by gkasprow** [comment]
I added such BGA heat sink to the DAC
![image](https://user-images.githubusercontent.com/4325054/189405665-b28f9a5a-79f8-4e2c-a37a-05956e793136.png)

**Comment by gkasprow** [comment]
The up-converters give off the heat using the thermal pad. We can glue some heat sink to the top but I don't think that it will help much. Anyway, I added two heatsinks.
![image](https://user-images.githubusercontent.com/4325054/189415653-4e55289b-0e48-4fde-9232-af652d385aca.png)
