### ISSUE TITLE
IC35 P1V8A supply is hot

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Phaser#145]
IC35 is power for P1V8A which supplies Si53340-B-GM (clock fanout). It is > 60 C (without fan). This seems anomalously hot. @gkasprow [noted](https://github.com/sinara-hw/Phaser/issues/116#issuecomment-698469813) that the current is nominal.

**Comment by gkasprow** [comment]
@jbqubit how are you cooling the board? Do you measure temperature with PCB lying on the table or, in the rack with airflow?

**Comment by jbqubit** [comment]
The board is lying on a table with no rack airflow. This will be better with forced air but wanted to bring this to your attention in case there's something odd going on.

**Comment by gkasprow** [comment]
the clock fanout consumes ~140mA and has 3.3-1.8V =1.5V dropout. It dissipates 0.2W of power. Should not be hot at all!
I'll look at it.

**Comment by gkasprow** [comment]
I didn't find anything suspicious. I added copper area around pins to lower Rth

**Comment by gkasprow** [comment]
![image](https://user-images.githubusercontent.com/4325054/189400935-117fcb57-1050-4fa1-b650-0a2a9a15c75d.png)
