### ISSUE TITLE
ADC input: floating

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#16]
* shield should be floating (there is a 100k to ground later)
* ~center should be dc coupled~ (already implemented)

**Comment by gkasprow** [comment]
OK, I didn't generate an assembly variant

**Comment by jordens** [comment]
Also: I'm ok with dropping the switchable termination. Few people use it and it needs space. But I'd still like a DNP 50 R termination.

**Comment by gkasprow** [comment]
added 49R9 0603.

**Comment by hartytp** [comment]
Currently (at least in the baseband variant) the SMA is not floating as it should be.

Also, I'd prefer to keep the switchable termination unless there is a good reason to remove it

**Comment by jordens** [comment]
#36

**Comment by gkasprow** [comment]
done. Added switchable termination and LED indicators on the front panel.
Removed 0R that shorts SMA to GND  but kept 10nF
