### ISSUE TITLE
analog input frontend complexity

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#19]
Maybe there is no need to support negative input voltages. Then maybe the area of analog input power supply, PGIA, analog frontend, multiple references derivation and signal shifting can be reduced in complexity.

**Comment by hartytp** [comment]
I'd like to keep negative voltages (e.g. I can imagine using the ADCs for phase locks). The circuit isn't particularly expensive and we have the board area + it's now well debugged and works nicely so I don't see a reason to remove it.
