### ISSUE TITLE
LO output

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#20]
![image](https://user-images.githubusercontent.com/1338946/68526955-cdb04580-02e1-11ea-9fcc-1969692de979.png)

I'd add the pullup R and the coupling C and u.fl on one of them.

And check https://github.com/sinara-hw/Phaser/issues/10#issuecomment-546233578 because min LO_OUT is larger than max REF_IN.

**Comment by gkasprow** [comment]
@jordens look here
![obraz](https://user-images.githubusercontent.com/4325054/68527800-7020f680-02eb-11ea-8ff3-41a3a2e732e3.png)
![obraz](https://user-images.githubusercontent.com/4325054/68527804-816a0300-02eb-11ea-9fad-f150d375ee9b.png)

**Comment by jordens** [comment]
That looks perfect.

**Comment by jordens** [comment]
I don't think you need a matched attenuator here though. LO_OUT is open collector and EXT_VCO is high impedance. Isn't there a simple discrete match?
