### ISSUE TITLE
SATA GTX

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#24]
Maybe instead of a bank of SATA connectors, there is something nicer to be done with those GTX. 

Opening up a path to cPCI serial here?

Two SATA connectors max for me.

**Comment by gkasprow** [comment]
The CPCIS controller and backplane we are currently working on assumes one GTP link per slot.
It's good idea to add a connector that in the future will expose this interface to the CPCIS connector.

**Comment by jordens** [comment]
I guess thats some mezzanine gigabit samtec connector now?

**Comment by gkasprow** [comment]
yes.
