### ISSUE TITLE
schematic cleanup

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#28]
Remove: 

![image](https://user-images.githubusercontent.com/1338946/68528267-b6c51f80-02f0-11ea-8ca7-b8ca62a01925.png)

No DDS here:

![image](https://user-images.githubusercontent.com/1338946/68528275-d8bea200-02f0-11ea-853b-e14cf4e2b7f0.png)

**Comment by gkasprow** [comment]
done
