### ISSUE TITLE
pulldown/up

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#30]
Assuming the FPGA has pullups during reset and configuration:

* DAC_RESETB should be pulled down (stronger than the FPGA and DAC pullups)
* DAC_SLEEP should be pulled up (stronger than the DAC pulldown)

**Comment by gkasprow** [comment]
done, I added 1k pull up/down

**Comment by jordens** [comment]
The one on SLEEP is not really necessary to make the boot well-defined and only consumes power. DNP it.

(nb The TRF already has a a PS power save active high which is good.)
