### ISSUE TITLE
sma_clk sel 

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#34]
Is 2V5 but the clock buffer is running off 1V8. Is the idea here that the 470Ohm resistor current limits, making this ok? 0.4V across 470Ohm is less than 1mA, which sounds ok, but are you confident this won't cause any issues (particularly sequencing issues/lock up/etc)?

**Comment by gkasprow** [comment]
The 1V8A wakes up together with P2V5 so I'm pretty sure it  would work.
Modern ICs require roughly 20mA or more to develop latchup.
