### ISSUE TITLE
variants

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#36]
both:

* PUDC: DNP R42
* SLEEP input: DNP R231

upconversion:

* DNP R184A/B

baseband:

* ADC input: DNP R156 R157 C31 C11 (#16)
* ~DNP the power supplies for the mixer~ I don't think there are any exclusive ones.
* Populate TR7 TR6 J15 J13
* Probably DNP L29 R38 L31 (and their colleagues in the other channels) for proper termination

**Comment by gkasprow** [comment]
done
