### ISSUE TITLE
IC12 supply

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#37]
Is there any reason this can't be supplied from a single rail to save power and make routing easier.

Need to double check min supply voltages, output head room and input common-mode range, but we may be able to get away with running this from 5V0A single-supply...

**Comment by hartytp** [comment]
From a look over the OpAmp data sheet this seems fine, but would be good to get a second pair of eyes before making a decision

**Comment by hartytp** [comment]
NB this also affects power sqeuencing for the ADC

**Comment by gkasprow** [comment]
we are operating far away from bottom power rails so we can connect V- to GND and V+ to 5VA
