### ISSUE TITLE
DAC LPF 

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Phaser#4]
I assume we need some LPF filter between DAC and the mixer. The LPF needs to be fully differential. We can go for this [one](https://www.minicircuits.com/WebStore/dashboard.html?model=DLFCG-540%2B), but there are not many options with different frequencies.

**Comment by jordens** [comment]
Or just a discrete one, like for the AD9148. Maybe not even such an aggressive 5th order. Yes, needs to be differential.
![image](https://user-images.githubusercontent.com/1338946/67196772-c2ad7800-f3fb-11e9-9467-26ce0e51e6f3.png)

**Comment by hartytp** [comment]
@gkasprow the MCL filter isn't the right approach IMHO. It only comes in a small range of values, none of which are what we'd ideally want (with 1GHz clock and 540MHz, you don't get much filtering for some of the lower frequencies we'll use).

I suspect that a well-designed discrete filter with tight-tolerance components will be the way to go

**Comment by hartytp** [comment]
@gkasprow how important is it to use a differential filter instead of, say, two single-ended filters?

**Comment by gkasprow** [comment]
The differential filter has usually better matching between negative and positive terminals. Moreover, depending on the construction, it may attenuate mainly differential components while two filters will attenuate both diff and common-mode components. Some differential filters are two single-ended ones in one package. So there is no simple answer to the question.
I don't think it is that important in our case.

**Comment by hartytp** [comment]
@gkasprow do you know of any other sources of any other manufacturers of SMT RF differential filters. I didn't see any at a look (but I might have missed one).

For the upconversion, I guess we'd really want a double differential filter for the I and Q channels to maintain amplitude and phase balance. So, it's not so clear to me that 4xsingle-ended is really worse than 2xdifferential.

Unless you're worried about this, I suggest we just go for standard MCL single-ended filters. I'd expect that the matching between filters will be better than the matching between discrete filters.

**Comment by gkasprow** [comment]
I'm not sure if lTCC would have tighter tolerance than a classical filter composed of 1% LC components.
They don't even specify the tolerance in DS.

**Comment by hartytp** [comment]
Ok. Are you happy designing a discrete differential LPF for this then? Since it needs to work to 1GHz, we'll have to be careful to simulate the parasitics correctly to get something that performs as expected.

**Comment by jordens** [comment]
I would also go for discrete. Third or fifth order like in the data-sheets and eval boards.

**Comment by gkasprow** [comment]
I will simply copy the eval board layout.

**Comment by gkasprow** [comment]
I plan to use this filter
![obraz](https://user-images.githubusercontent.com/4325054/68335832-7e99c300-00dd-11ea-9714-c14a76e4db07.png)

**Comment by hartytp** [comment]
Cool!

Questions:
- the dac/modulator there aren’t the ones we’re using. Does that matter (different parasitics)
- will you use the same BOM lines as the eval board to keep the parasitic the same?
- how much will the layout affect the response?
- do you have a curve of the filter response? If not, can we do a quick sim with all component models
- are you using components with very tight tolerances (eg the i and q channels need really good matching to preserver the mixers excellent side and suppression)

**Comment by gkasprow** [comment]
I'm using 2% inductors and capacitors in the 0603 packages to make modifications easier. I will remove the lower layers of PCB to limit the parasitics. We are talking about 2 components 68nH and 2.7pF. In the case of the capacitor, the influence of its parasitic capacitance is critical and I'm not sure if we can precisely simulate such a circuit. EVKIT does not have any filter.
The DACs have current outputs that are loaded with 50R. It's hard to say if its parasitics matter that much.

**Comment by gkasprow** [comment]
Anyway, I will estimate pads capacitances and do the simulation.

**Comment by gkasprow** [comment]
The very first approach
![obraz](https://user-images.githubusercontent.com/4325054/68349283-f1fefd00-00fc-11ea-8431-90f375096886.png)
and the charasteristics:
![obraz](https://user-images.githubusercontent.com/4325054/68349313-0a6f1780-00fd-11ea-99bc-ba8c155d4178.png)

**Comment by gkasprow** [comment]
This schematic includes all parasitic components
![obraz](https://user-images.githubusercontent.com/4325054/68380272-cb1de680-014f-11ea-8dbe-459480f2eaf9.png)
![obraz](https://user-images.githubusercontent.com/4325054/68380288-d40eb800-014f-11ea-8e7d-f19a7aedeafb.png)

**Comment by jordens** [comment]
ok. @hartytp I think this is probably worse than 0.1 dB flatness over 20 MHz already at 300 MHz.

**Comment by hartytp** [comment]
> ok. @hartytp I think this is probably worse than 0.1 dB flatness over 20 MHz already at 300 MHz.

Indeed. 0.1dB is better than we need (just 1dB is a bit on the high side, but nought-dot-a-few-dB is ok).

**Comment by hartytp** [comment]
Thanks greg, that looks pretty good. What are the inductor part numbers?

**Comment by gkasprow** [comment]
Coilcraft 0603HP-68NXGLU
