### ISSUE TITLE
Ic21 PGFB

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#43]
since we use the PG, don't we need to connect PGFB to Vout via a suitable divider. 

![image](https://user-images.githubusercontent.com/21218399/68584410-6a581c00-0477-11ea-9bac-87695ba15fa4.png)

**Comment by gkasprow** [comment]
added 
![obraz](https://user-images.githubusercontent.com/4325054/68759492-12a0e880-0610-11ea-9e0b-6074f9c2d4ed.png)

**Comment by jordens** [comment]
crossref: https://github.com/sinara-hw/Fastino/issues/40
