### ISSUE TITLE
Clock fanout power

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#44]
Shouldn't this be powered from an LDO to avoid getting large SMPS spikes on the DAC output?

**Comment by hartytp** [comment]
NB this should ideally power on after the DAC 1V2 supply to avoid sequencing issues

**Comment by hartytp** [comment]
Also, are you happy with the power sequencing of the fanout buffer supply relative to the modulator/DAC power supplies?

**Comment by gkasprow** [comment]
The clock buffer supply (P1V8) wakes up after DAC P1V2A and modulator P3V3A   so it is fine.

**Comment by hartytp** [comment]
> The clock buffer supply (P1V8) wakes up after DAC P1V2A and modulator P3V3A so it is fine.

Yes, you're right. So, no sequencing issue. However, I'm still a little concerned about running this from a SMPS. It's low power so can't we just use a LDO?

**Comment by hartytp** [comment]
> NB this should ideally power on after the DAC 1V2 supply to avoid sequencing issues

I think I just got confused between the 1V2 and 1V2A rails. As you say, the sequencing looks correct.

**Comment by gkasprow** [comment]
OK, let's make the 1V8A rail then out of 3.3V
