### ISSUE TITLE
DAC CLKVDD

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#47]
Is a ferrite sufficient isolation between the (noise sensitive) CLKVDD supply and the DACVDD/DIGVDD supplies? Should this have an LDO?

**Comment by hartytp** [comment]
Simillarly, for DACVDD (noise sensitive) and DIFVDD (digital noisy rail)

**Comment by hartytp** [comment]
On the eval board it looks like the clk and analog supplies come from an LDO and are isolated by a ferrite, while the digital supply comes directly from a SMPS. Worth copying that? 

![image](https://user-images.githubusercontent.com/21218399/68591341-6c76a680-0488-11ea-926f-24048d9bb0b7.png)

**Comment by hartytp** [comment]
same goes for running the IO rails from the same supply as analog rails. Surely better to run the LVDS rail directly from an SMPS rather than running it from the sensitive analog rail???

**Comment by hartytp** [comment]
Equally, are we happy with the decoupling between the DAC and modulator supplies?

**Comment by gkasprow** [comment]
All the specs in the datasheet are usually taken with eval kit, so if we are happy with them, I'd simply copy that. And this is what I did. I can add a dedicated LDOs for digital signals if this makes you sleep better :)
In the case of the modulator, we are mainly affected by RF. I used 1k Ferrite beads as suggested in the DS.
Again, I can replace this big LDO with 3 smaller ones if we need better separation, but I don't think that it would be an issue. More important is how we route the signals on the PCB.

**Comment by hartytp** [comment]
> All the specs in the datasheet are usually taken with eval kit, so if we are happy with them, I'd simply copy that. And this is what I did. 

I don't think so, see my post above.

This part of the eval schematic shows that the DAC analog rails are generated from LDOs, while the digital parts are generated from a SMPS.

There are then additional ferrites used for decoupling.

> Again, I can replace this big LDO with 3 smaller ones if we need better separation, but I don't think that it would be an issue. More important is how we route the signals on the PCB.

Okay, that makes sense.

**Comment by hartytp** [comment]
@gkasprow the design still does not follow the eval board. Look at the image below. The DAC digital supplies come direct from a SMPS while the analog supplies come from a dedicated LDO. This allows them to be well decoupled from the digital. In contrast, we just use a FB.

![image](https://user-images.githubusercontent.com/21218399/69078753-75d7b400-0a30-11ea-86c0-14b7517a1dbd.png)

**Comment by gkasprow** [comment]
OK, we can then connect it to P1V2 which is also generated by an LDO and is used to supply the FPGA.
We can also add another LDO, dedicated to digital part of DACs.

**Comment by hartytp** [comment]
@gkasprow we should fix this before routing as it affects power planes

**Comment by gkasprow** [comment]
I copied P1V2A LDO and connected it to DIGVDD. IT should solve the issue.
![Uploading obraz.png…]()

**Comment by hartytp** [comment]
Pic didn’t upload :( isn’t it better to drive from a smps to avoid significant power dissipation in the ldo?

**Comment by gkasprow** [comment]
we don't have 1V2 SMPS rail.
![obraz](https://user-images.githubusercontent.com/4325054/69858804-12048500-1293-11ea-8927-c033ce8288f2.png)

**Comment by gkasprow** [comment]
anyway, 300mV drop * 600mA = 180mW.

**Comment by hartytp** [comment]
I was suggesting adding a new rail but I agree if the ldo drop out is really that low it’s fine
