### ISSUE TITLE
terminate the Q channels in baseband mode

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#48]
In baseband mode, should we terminate the unused Q output? This termination should obviously be removed when the UFL is used.

**Comment by jordens** [comment]
It's better to sleep those DACs or scale them to 0. That saves power and crosstalk.
On the contrary: the external termination for the mixer should be DNPed for baseband.

**Comment by gkasprow** [comment]
@jordens right, the LRL circuit should be kept open.
