### ISSUE TITLE
PLL LPF

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#49]
@WeiDaZhang can you check you're happy with the current DAC PLL loop filter please?

![image](https://user-images.githubusercontent.com/21218399/68591625-0e968e80-0489-11ea-8864-854a66014ca7.png)

**Comment by hartytp** [comment]
Same for the modulator LPF

![image](https://user-images.githubusercontent.com/21218399/68592756-b9a84780-048b-11ea-80d0-e30dbb2c9b40.png)

**Comment by WeiDaZhang** [comment]
There is not much information provided about the loop filter, apart from a paragraph at top page.4
https://www.ti.com/lit/pdf/SLAA520?jktype=tech_docs
The suggestion would be:

1. Not to use the on-chip PLL, unless one has to do so.

2. Not to make the divide ratio greater than 120 when using the on-chip PLL, and therefore avoid external loop filter, unless one has to do so.

3. Use the default loop filter setting which is as the schematic is.

**Comment by hartytp** [comment]
> Not to use the on-chip PLL, unless one has to do so.

Why? From the DAC data sheet, it seems pretty nice.

> Not to make the divide ratio greater than 120 when using the on-chip PLL, and therefore avoid external loop filter, unless one has to do so.

I don't follow? Why is the divider connected to using an external loop filter? In our case, the DAC clock will be 1GHz with 125MHz ref (max f_pfd is 155MHz according to data sheet). 

> Use the default loop filter setting which is as the schematic is.

Okay, let's do that then...

**Comment by jordens** [comment]
Because there is already an internal LF

![image](https://user-images.githubusercontent.com/1338946/68603894-87a5de00-04a9-11ea-8f3d-75b16868562d.png)

But please add a 0R and a bit of space to that pin:

![image](https://user-images.githubusercontent.com/1338946/68604045-dd7a8600-04a9-11ea-8c2c-f5c693c0a780.png)

**Comment by WeiDaZhang** [comment]
> > Not to use the on-chip PLL, unless one has to do so.
>
> Why? From the DAC data sheet, it seems pretty nice.]

It was said in the document, however, taking a closer look.
![image](https://user-images.githubusercontent.com/22749113/68605435-4c54e080-04a4-11ea-9923-fffa853e1975.png)
To put it in a graph we had before, it seems quite good, you are right.
![image](https://user-images.githubusercontent.com/22749113/68606199-d5b8e280-04a5-11ea-8191-a005b0641a49.png)

**Comment by hartytp** [comment]
Thanks @jordens @WeiDaZhang 

@WeiDaZhang what about the upconverter LF? are you happy with that?

**Comment by gkasprow** [comment]
>But please add a 0R (DNP) and a bit of space to that pin:

@jordens do you want to have the LF disabled by default?

**Comment by jordens** [comment]
Yes. We are looking at P*M < 64 for 125 MHz and < 80 for 100 MHz reference in. 10 MHz wouldn't work anyway.

**Comment by hartytp** [comment]
@WeiDaZhang please can you confirm that you're happy with the upconverter LF asap and then close this? Thanks!

**Comment by WeiDaZhang** [comment]
I'm looking at it. What's the frequency PFD? I suppose it's 125MHz?

**Comment by WeiDaZhang** [comment]
@hartytp

**Comment by jordens** [comment]
62.5 MHz

**Comment by WeiDaZhang** [comment]
This one should work. I've tried for two frequencies.
The VCO gain is not clear, I assumed (4800-2400)/5 = GVCO (MHz/V) when VCO range DIV = 1 selected. If the tuning voltage is actually 3.3V, there will be a loop bandwidth error but should remain stable.
I've allowed relatively wide loop bandwidth assuming the reference is much lower noise than the VCO even with frequency scaled.
![image](https://user-images.githubusercontent.com/22749113/69089111-b559cc80-0a3f-11ea-8b84-218ccab228b0.png)
![image](https://user-images.githubusercontent.com/22749113/69084826-f2708f80-0a3c-11ea-9fad-d3d387a4d276.png)
C1       C2        R2    C3    R3    C4    R4
120p   3000p  330   33p  330  33p  330

**Comment by hartytp** [comment]
@gkasprow can we go for @WeiDaZhang's loop filter please? Once the boards arrive, we'll test this on a phase noise meter and optimise the loop filter further.

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/69833270-04b7ae00-1233-11ea-9cf6-531b3bce1166.png)

**Comment by pathfinder49** [comment]
> > > Not to use the on-chip PLL, unless one has to do so.
> > 
> > 
> > Why? From the DAC data sheet, it seems pretty nice.]
> 
> It was said in the document, however, taking a closer look.
> ![image](https://user-images.githubusercontent.com/22749113/68605435-4c54e080-04a4-11ea-9923-fffa853e1975.png)
> To put it in a graph we had before, it seems quite good, you are right.
> ![image](https://user-images.githubusercontent.com/22749113/68606199-d5b8e280-04a5-11ea-8191-a005b0641a49.png)

@hartytp What's the conclusion here? Is the idea to use the DAC PLL or bypass it?

**Comment by hartytp** [comment]
> @hartytp What's the conclusion here? Is the idea to use the DAC PLL or bypass it?

Depends on the application.

Using the DAC/upconverter PLL and clocking from Kasli is generally the most convenient way of setting things up. In many cases that will be completely fine from a noise perspective.

If one needs the lowest possible noise then an external clock/LO will definitely give better results than using an internal PLL from the DAC / upconverter. NB the DAC clock is generally much less important than the upconverter (if it's being used) since, all things equal, phase noise scales like `20*log10(frequency)` so for a 3GHz carrier and 300MHz IF, one is 20dB more sensitive to the upconverter LO.

My advice would be to measure the phase noise for the upconverted RF and then decide if it's good enough for the gate. Using an external microwave source for the LO / DAC clock is there are a fallback plan if we decide it's needed.
