### ISSUE TITLE
DAC pull ups

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#51]
Isn't 1k a bit aggressive for the sleep and RESET pull-ups?

**Comment by gkasprow** [comment]
the input current is +/- 40uA + FPGA bias current of 15uA
with 10k we can get 550mV of drop.
But with Artix pullup  of 330uA enabled, we may need 1k to make sure that the DAC is in reset state.

**Comment by jordens** [comment]
1k RESETB pulldown is fine for me. But leave out the SLEEP pullup
