### ISSUE TITLE
PI

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#52]
@gkasprow we should be careful about PI (including voltage drops across FBs) for the high-current rails. e.g. DIGVDD on the DAC

![image](https://user-images.githubusercontent.com/21218399/68592258-82856680-048a-11ea-85ce-225f51e535fb.png)

**Comment by hartytp** [comment]
May be worth considering connecting a regulator Vsense to a point near the DAC to cancel out trace/FB voltage drops

**Comment by gkasprow** [comment]
I will make sure that during PI analysis max voltage drop is set to let's say 10mV. I'll add note about it.
