### ISSUE TITLE
modulator input termination

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#54]
Don't the modulator baseband inputs need external termination (see eval board)?

**Comment by hartytp** [comment]
![image](https://user-images.githubusercontent.com/21218399/68592619-6a621700-048b-11ea-8315-8a99b713b918.png)

**Comment by jordens** [comment]
They have termination just like in the datasheet.

![image](https://user-images.githubusercontent.com/1338946/68594414-c59a0680-0497-11ea-8481-342e53b8c7f0.png)

**Comment by gkasprow** [comment]
We should place this termination circuit after the 0R option selectrion resistors. I will move them to the mixer page.

**Comment by hartytp** [comment]
okay, just keep the layout as tight as possible to minimize parasitics and make sure there is very close matching between the I and Q channels
