### ISSUE TITLE
modulator ref coupling capacitor

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#56]
Isn't 4p7 a bit small for a 125MHz ref clk?

![image](https://user-images.githubusercontent.com/21218399/68592828-e0667e00-048b-11ea-96b9-a9c978e8caa1.png)

**Comment by hartytp** [comment]
sorry, this isn't for a reference. Still, any reason to use such a small capacitor here?

**Comment by gkasprow** [comment]
it was used in the devkit so I copied it.

**Comment by jordens** [comment]
it's a high impedance input, probably the same 4-5k || a few pF as the other inputs.

**Comment by hartytp** [comment]
okay, true, in that case let's leave it as is

**Comment by hartytp** [comment]
hmm...I still would have thought we'd want to the coupling capacitance a bit higher. Otherwise we have a significant divider ratio with the input capacitance if it's a few pF. Is there any downside in using 100pF?

**Comment by gkasprow** [comment]
OK, let's go for 100p

**Comment by jordens** [comment]
The downside to large coupling capacitors is worse low-f rejection (power supplies on these single-ended lines) which becomes phase noise once it hits the input buffers. Let's leave it for tweaking later.
