### ISSUE TITLE
FP BB/UC LED

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#57]
To indicate which variant is populated

**Comment by jordens** [comment]
Can't we just put some marking/label on the panel? Using a LED for something that's guaranteed to not change is bad. I'd rather use that one remaining LED to signal external clock input selection. The other LEDs are all channel-associated.

**Comment by hartytp** [comment]
Okay, I'm fine with adding some text to the panels (separate LEDs felt easier than different panels). So long as there is a clear external marking.

**Comment by jordens** [comment]
Alternatively we can sacrifice one of the 8 channel LEDs to talk about variants. E.g. red for baseband and blinking red for Mixer PLL unlocked.

**Comment by gkasprow** [comment]
we will have other FPGA bits anyway.
I will make two panel designs as we have for Urukul.

**Comment by gkasprow** [comment]
There is a variant signal routed to FPGA. It can be forwarded to the LED. So we can have both panel annotation and LED.
