### ISSUE TITLE
EXT VCO attenuator

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#59]
I couldn't see where in the data sheet it says we need this: 
![image](https://user-images.githubusercontent.com/21218399/68593844-389e7f80-048e-11ea-9f7f-84a414803fde.png)

I did see that -10dBm was the value they happen to use in some plots, but I didn't see any indication that this is a requirement...

**Comment by hartytp** [comment]
Also, this should be DNP in the BB variant. FWIW I would have thought we could do this with standard resistors since it doesn't need to be precise...

**Comment by gkasprow** [comment]
It depends on what frequency we will pass thgrough this path.
OK, let's add resistive divider.

**Comment by hartytp** [comment]
@gkasprow if you think that 4GHz through a resistive divider is problematic then please do keep the attenuator (assuming we need it but, as I said, I didn't find a spec for the LO power the modulators want).

**Comment by gkasprow** [comment]
this could be problematic for the standard resistors. But since we don't know if we need it, lets switc hto resistors anyway.

**Comment by hartytp** [comment]
hmm...before closing this it would be better to decide if the attenuator is actually needed.

Let's leave the packaged attenuator for now and an action on me to figure out what LO power is wanted.

**Comment by gkasprow** [comment]
we can always place one with other attenuation. 0R 0402 resistor can be soldered as well instead of it.

**Comment by hartytp** [comment]
@gkasprow was the plan to put a pad 0402 resistor that can be used to bypass this attenuator?

**Comment by gkasprow** [comment]
Yes. it can be soldered directly to the attenuator pads.

**Comment by gkasprow** [comment]
I added 0R to make sure it can be placed by P&P machine
