### ISSUE TITLE
LO distribution

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Phaser#6]
HMC has a differential output that could drive two mixers, one with 180-degree phase shift. Do we go for this or we use ADCLK buffer or even passive splitter?

**Comment by hartytp** [comment]
Let's look at the power levels. But, a passive differential splitter may be the best option.

**Comment by hartytp** [comment]
@gkasprow can you give me permissions to close/edit other people's issues please? I'd like to close this

**Comment by gkasprow** [comment]
@hartytp done

**Comment by hartytp** [comment]
thanks
