### ISSUE TITLE
baseband amplitude

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#60]
Currently the path between the DAC and the mixer leads to some 0.5 V (25 Ohm, 20 mA) full scale current (peak single ended) by default. The mixer seems to have optimal performance (OIP3 e.g.) around 0.5 V single ended RMS, i.e. 0.71 V peak single ended and is specified up to 1 V RMS SE (1.4 V peak SE). On top there'll be some losses in the AA filter.

Proposal: use a 1:4 transformer after the AA filter to get 1 V peak SE at the mixer input. This matches the mixer input range better. That space is needed anyway for the baseband variant baluns. It gives more power at the output in both variants. There is a coarse full scale adjustment to fine tune it further. Also the eval board uses the 1:4 transformer. This does change the filter design though AFAICT.

There is `coarse_dac` for fine tuning the full scale current.

![image](https://user-images.githubusercontent.com/1338946/68594677-5ec91d00-0498-11ea-9ebf-f7f103da62ce.png)

On the other hand the mixer datasheet talks about "VinBB = 300 mVrms single-ended sine wave in quadrature" as their favorite characterization default. So maybe 500 mV peak SE per quadrature is just right.

Also c.f. https://github.com/sinara-hw/Phaser/issues/21#issuecomment-552210181

**Comment by hartytp** [comment]
> 20 mA

Isn't the DAC 30mA FS?

**Comment by jordens** [comment]
20 mA typ.

**Comment by hartytp** [comment]
> 20 mA typ.

IIRC there is a resistor one picks dependent on the FS current and the one we used is for 30mA. Maybe I'm wrong though...

**Comment by jordens** [comment]
You'd operate it with `coarse_dac` setting it to 20 mA FS.

**Comment by hartytp** [comment]
Okay, but should we change `BIASJ` then?

**Comment by jordens** [comment]
No. It's the product of both.

**Comment by hartytp** [comment]
okay, thanks for clarifying.

Anyway, this sounds like a good idea.

What's the 1:1 balun for?

**Comment by hartytp** [comment]
@dtcallcock what's the actual min frequency you want? 1MHz or lower?

It looks like that 1:4 should be fine though

![image](https://user-images.githubusercontent.com/21218399/68594831-4b19b880-0490-11ea-81f2-33f15ce83c3d.png)

**Comment by jordens** [comment]
I guess that two-transformer combo blocks common mode effects (e.g. the primary secondary capacitive coupling which is an intrinsic limitation in single-core baluns) a bit better. Don't know any numbers though.

**Comment by jordens** [comment]
On the other hand the mixer datasheet talks about "VinBB = 300 mVrms single-ended sine wave in quadrature" as their favorite characterization default. So maybe 500 mV peak SE per quadrature is just right.

**Comment by hartytp** [comment]
It does look like the mixer is designed to connect to a DAC without a balun:

![image](https://user-images.githubusercontent.com/21218399/68597077-3f2ff580-0494-11ea-9fd8-f74fe3452c65.png)

Unless I'm missing something, DAC3283 looks very similar to 34H84 with regards to outputs...

**Comment by hartytp** [comment]
No, never mind, it is a bit different

**Comment by dtcallcock** [comment]
> @dtcallcock what's the actual min frequency you want? 1MHz or lower?

1 MHz should be good but it'd be nice to have at least somewhat graceful degradation down to around 300kHz if possible.

There are better and smaller 1:4 baluns for the lower frequency end (eg. [TC4-1TX+](https://www.minicircuits.com/pdfs/TC4-1TX+.pdf).  What upper frequency are you shooting for with the BB variant though?

**Comment by hartytp** [comment]
> There are better and smaller 1:4 baluns for the lower frequency end (eg. TC4-1TX+. What upper frequency are you shooting for with the BB variant though?

This is just on the DAC, so I think the choice here is agnostic of which variant we're using; both need to go up to around 400MHz.

**Comment by dtcallcock** [comment]
It says the TC4-1TX+ is useable to 450MHz but they don't spec it above 300MHz.  The [TC4-6TX+](https://www.minicircuits.com/pdfs/TC4-6TX+.pdf) has worse performance but the return loss holds up better above 200MHz and it's specified up to 600MHz.

**Comment by jordens** [comment]
The current AA filter is already 10 dB down at 400 MHz. I wouldn't worry about the balun adding another ~3 dB.

**Comment by gkasprow** [comment]
I assume we leave it as it is now.
