### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#61]
Great work on this @gkasprow 

I've completed my review of the schematics. Assuming @jordens has also completed his, I'd say we can close the schematic review here.

**Comment by jordens** [comment]
I'm done with the schematic review.

**Comment by hartytp** [comment]
Cool.

What's the time line for getting this to manufacture @gkasprow ?

**Comment by gkasprow** [comment]
Once I fix all the issues, the layout will be continued by @CannaCardo

**Comment by gkasprow** [comment]
I plan to fix them within a day.

**Comment by hartytp** [comment]
@CannaCardo what's your timeline for the layout? Do you think you can do it this week?

**Comment by hartytp** [comment]
@CannaCardo ping...

**Comment by CannaCardo** [comment]
Sorry, I didn't see the notification. The rough layout should be done later today
