### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Phaser#65]
@CannaCardo it's your turn with layout and routing
- copy stack up from Kasli, the same with rules
- copy position of IDC connector and assembly holes from Urukul
- make component placement, once finished post it for review
- then during routing follow strictly reference design for ADC and upconverter

**Comment by gkasprow** [comment]
also:
- add missing diff nets and directives
- if you encounter any difficulties, open an issue
- if you have some questions, want propose some changes, open issue
- if you find some bug, open issue.

**Comment by jordens** [comment]
I think a couple of issues were addressed incorrectly. Like the ufl for the baseband q output, the baseband balun type, the upconverter balbal option and bypass jumper design, the input shield grounding.

**Comment by hartytp** [comment]
> Like the ufl for the baseband q output

What's the issue here? Are you not ok with MMCX?

**Comment by hartytp** [comment]
> bypass jumper design

What do you want done differently here?

**Comment by hartytp** [comment]
@jordens I've done a second review focussing on the items we raised previously and opened issues where necessary. Did you spot anything I've missed?

**Comment by jordens** [comment]
The baseband q output doesn't need to be MMCX. It's very much debugging or prototyping only. MMCX is much bigger and pierces though all layers. Baseband Q would be disabled by default and should be DNP in later variants.

The bypass jumper should be as discussed elsewhere. It is not. There should be the same transformer footprint, populated with a single ended secondary for baseband or DNPed (but optionally a 1:4 or 1:2 to increase amplitude) and differential output plus differential termination into the mixer for uconverter.

I had spotted the issues I mentioned above.

**Comment by hartytp** [comment]
> The bypass jumper should be as discussed elsewhere. It is not. There should be the same transformer footprint, populated with a single ended secondary for baseband or DNPed (but optionally a 1:4 or 1:2 to increase amplitude) and differential output plus differential termination into the mixer for uconverter.

Is this all covered by https://github.com/sinara-hw/Phaser/issues/21 ?

**Comment by jordens** [comment]
yes.

**Comment by jordens** [comment]
Check out http://jordens.github.io/sandbox/ by the way. Smaller than the PDFs, faster on mobile, nice for layouts. If someone wants to extend and manage this for to all sinara-hw projects feel free.

**Comment by gkasprow** [comment]
I found u.fl connectors very fragile and treat them only for debugging.
I can use SMT MMCX if you want to use them more than once:)

**Comment by gkasprow** [comment]
@jordens is there a way one can generate automatically a link for the design? I'd love to place such one in wiki of every project.

**Comment by jordens** [comment]
Sure. This can be automated and maintained. Somebody would have to do it though.

**Comment by jordens** [comment]
Ok. You choose the connector. Of it works I don't mind either way.

**Comment by hartytp** [comment]
So long as there is space, I definitely prefer MMCX for this.
