### ISSUE TITLE
squencing annotation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#66]
@gkasprow I still don't understand this annotation.

![image](https://user-images.githubusercontent.com/21218399/69078453-ddd9ca80-0a2f-11ea-9349-fc15514879f3.png)

What do `ADC` and `DAC` mean here? Isn't the ADC just the P5V0A supply?

**Comment by hartytp** [comment]
https://github.com/sinara-hw/Phaser/issues/15#issuecomment-552407243

**Comment by gkasprow** [comment]
yes, it is.

**Comment by gkasprow** [comment]
fixed
