### ISSUE TITLE
DAC output caps

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#68]
What are these 100nF caps to groudn for? 
![image](https://user-images.githubusercontent.com/21218399/69080602-36ab6200-0a34-11ea-8640-8bbebe39cd26.png)

**Comment by gkasprow** [comment]
They are to short N input of mixer to GND in single ended mode (balun bypass)

**Comment by jordens** [comment]
The balbal bypass should be differential. https://github.com/sinara-hw/Phaser/issues/21#issuecomment-556991747

**Comment by jordens** [comment]
I think this is resolved since  85c311d
