### ISSUE TITLE
Layout 

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Phaser#73]
- [x] swap J9 and SATA connectors. Otherwise CPCIS adapter won't have access to the J9. One can swap transceivers if needed.
- [x] separate channels with L28, L36 etc . The inductors may couple and cause crosstalk
- [x] U can swap IC5 outputs

**Comment by gkasprow** [comment]
- [ ] do not place vias in pads. U can switch to 0201 caps under FPGA to fit them between vias. make sure that via hole does not touch the component pad. Otherwise, it will suck the tin.
- [ ] don't even try routing on 6 layers. Move to 8 or copy the stackup from Kasli. Use the Brandner web tool for stackup creation.

**Comment by gkasprow** [comment]
- [ ] move LM75 closer to the heat source: ADC and upconverter

**Comment by jordens** [comment]
I think kasli is 6 layers. Would be nice to not have to go beyond kasli.

**Comment by gkasprow** [comment]
Kasli is purely digital board. It has only one ground plane. Doing Phaser with only 6 layers would be tricky.

**Comment by gkasprow** [comment]
Anyway, let's try to copy the DAC layout/routing from evkit and see how many layers it needs.

**Comment by hartytp** [comment]
@gkasprow can you finish off the remaining schematic issues please?

**Comment by hartytp** [comment]
@CannaCardo good work. Can we have the top/bottom side renders in the PDF as well please?

**Comment by CannaCardo** [comment]
Renders added

**Comment by hartytp** [comment]
Thanks! Do you think we can get the boards off to manufacture this week?

**Comment by CannaCardo** [comment]
Most likely :)

**Comment by hartytp** [comment]
Amazing, THANK YOU!

**Comment by dtcallcock** [comment]
First 4 SMAs are labeled RF OUT 0-3 on silkscreen.

**Comment by hartytp** [comment]
how's the layout going @CannaCardo ?

**Comment by gkasprow** [comment]
I took over the design to implemented all fixes. Then I will pass it to @CannaCardo to finish. I should finish them today.

**Comment by hartytp** [comment]
Aah, ok, makes sense! Thanks! (I have too many projects on the go and am trying hard to get them finished)

**Comment by gkasprow** [comment]
well, at the moment I have 17 projects going. Sinara is one of them. Some of them started 10years ago and don't want to finish...

**Comment by gkasprow** [comment]
@CannaCardo during finishing the routing make sure that:
- [ ] no components are placed close to the FPGA to enable assembly of the heatsink latch
- [ ] follow precisely routing of the upconverter chip Now the decoupling capacitors are far from the IC pins. The inductors or ferrite beads can be on the bottom layer or far away but the caps must follow the datasheet recommendation. Lower capacitors values must be installed closer to the IC
- [ ] All QFNs have vias in the thermal pad
- [ ] all test point, LEDs and connectors have labels which indicate their function
- [ ] all ICs, diodes, connectors, and inductors, transformers have their designator enabled. Use 1mm high font, 0.2mm stroke
- [ ] all vias in thermal pads are unmasked on the opposite side to prevent from acid pocket formation
- [ ] there are at least 2 different fiducials per side on top and bottom. Use small ones.

**Comment by hartytp** [comment]
Thanks @gkasprow ! Can you post a new rc so we can sign off on the schematic please?

**Comment by gkasprow** [comment]
one moment.

**Comment by gkasprow** [comment]
the latest release is here
https://github.com/sinara-hw/Phaser/releases/tag/v1.0rc5
@CannaCardo you can take over the project and finish the routing.

**Comment by jordens** [comment]
And put exposed polygons on the bottom layer under the two mixers like we have for the DDS on Urukul.

**Comment by jordens** [comment]
And make sure that there are no tall components (that big capacitor) on the bottom that would interfere with card insertion.

**Comment by jordens** [comment]
And Greg's point from above is not honored. You really need to spread out the signal paths after the DACs, especially the inductors. Even within a single diff pair the coupling between the two inductors is problematic as it reduces the filtering.

**Comment by jordens** [comment]
And PI simulation. There are some really carved up polygons.

**Comment by hartytp** [comment]
AFAICT all schematic review items were correctly implemented. Good work!

Layout is coming along nicely @CannaCardo! Really looking forward to getting my hands on phaser. Good work all.

**Comment by hartytp** [comment]
@jordens assuming you have no objections, I suggest we freeze the schematic here.

**Comment by hartytp** [comment]
@CannaCardo whats the status of this? Are we on track to get the boards to manufacture next week?

**Comment by CannaCardo** [comment]
I've got almost all of the issues here done, few traces with length matching (mainly DAC area) and PI simulation are left.

**Comment by hartytp** [comment]
Ace :)

So ready for review early next week sounds about right then? That would be wonderful

**Comment by CannaCardo** [comment]
Yes. I've finished other projects, so there are no excuses now  :)

**Comment by hartytp** [comment]
@gkasprow can you do a layout review?

**Comment by dtcallcock** [comment]
Just noticed that R49 is still populated on baseband version.

**Comment by gkasprow** [comment]
I finished my review

**Comment by hartytp** [comment]
@gkasprow @CannaCardo a few questions:
-are you satisfied that all converters follow eval board / data sheet recommendations for the layout?
- are you happy with the digital to analog isolation and isolation of the analog from the fpga + converters?
- are the I/q channels perfectly matched? We need to avoid any asymmetry to keep the sideband suppression good
- happy with Si for high speed and analog traces?

**Comment by gkasprow** [comment]
@CannaCardo, please mark remaining "ticks" above.

**Comment by hartytp** [comment]
- happy with layout and routing of the rf signals to give good si and minimise parasitical in filters etc

**Comment by gkasprow** [comment]
Once all the issues I posted are addressed, I would be happy.
In the end, I will make a few GND cutouts to limit the spreading of EMI from DC/DC to RF part.

**Comment by hartytp** [comment]
Copying the only unchecked issue from above:

- [ ] follow precisely routing of the upconverter chip Now the decoupling capacitors are far from the IC pins. The inductors or ferrite beads can be on the bottom layer or far away but the caps must follow the datasheet recommendation. Lower capacitors values must be installed closer to the IC

**Comment by hartytp** [comment]
Anyway, very excited that we're now so close to getting this off. Just Booster after this...

**Comment by hartytp** [comment]
One really nit picky thing that you may feel isn't worth it...
- [ ] on stabilier all the power TPs and LEDs are in a row with a couple of GND pads there as well. That made spotting mistakes and checking supplies really quick (don't need to search for them and you can really see if one supply isn't coming on properly). If it's not too much work we should to that here as well

**Comment by CannaCardo** [comment]
>  on stabilier all the power TPs and LEDs are in a row with a couple of GND pads there as well.

I've added GND pads visibly near the testpoints, should be easy to find

**Comment by hartytp** [comment]
What was nice on Stabilizer was that all TPs and LEDs were in a row, so one could check all power rails by eye really quickly without having to search over the board. That's much nicer than having them scattered over the board. But, I understand if it's too much work to do that now.

**Comment by CannaCardo** [comment]
I'll keep that in mind with future boards ;)

**Comment by hartytp** [comment]
@CannaCardo how's this going? Any chance of getting another RC today so we can do our final reviews over the weekend and send off to production on Monday?

**Comment by CannaCardo** [comment]
I added the next RC, still without PI/ copper balancing as I don't have access to a hyperlynx license at the moment.

**Comment by gkasprow** [comment]
I will simulate it with Ansys PDN or CST PDN over the weekend. I have a private license for both.

**Comment by hartytp** [comment]
@CannaCardo awesome! Did you folow the upconverter reference design layout? If so, I think all issues here are resolved and we can close this. Well done.

**Comment by CannaCardo** [comment]
Yes, the image on the schematic is upside-down compared to the PCB

**Comment by hartytp** [comment]
Great, thanks!

**Comment by gkasprow** [comment]
yes, layout is OK, but I still don't think the ref design is done correctly:)

**Comment by hartytp** [comment]
@gkasprow are you happy with the layout? In particular the usual things like:
- loop area in high-frequency/low-noise (LF etc) signals?
- position of decoupling capacitors
- IQ and channel-channel matching/symmetry
- noise sources (SMPSs/digital traces)
- controlled impedances

etc? If so let's close this and send to manufacture after PI

**Comment by hartytp** [comment]
@gkasprow thanks for doing all that!

It looks like most open issues can be closed now. What’s left to do? Can you post a final rc once all changes are complete so we can sign off?
