### ISSUE TITLE
Mmcx ref clock input location

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#74]
Should be as far back as possible. And the cable should not interfere with the eem ribbons, the sata cables or the J9 high speed connector and its counterpart.
The location of the mmcx on urukul and mirny near the front panel is not very good.

Jtag on the other hand can be pretty much anywhere. No need for it to be in the back.

Probably the samtec gigabit hermaphroditic connector should be located where the jtag connector is now. But it should be in a location where its corresponding connector on the cPCI-S adapter does not interfere with anything on any of the existing other EEM module (e.g. should not interfere with the +-15 V modules on Zotino/Fastino/Sampler, @gkasprow should check this).

**Comment by CannaCardo** [comment]
Would here be ok, considering the CPCIS adapter?
![image](https://user-images.githubusercontent.com/18137374/69543959-fcd7df80-0f8e-11ea-9eef-f57cc55e70fd.png)

**Comment by jordens** [comment]
The current cPCI-S design has a specific MMCX clock output that derives it from a diff pair on the cPCI backplane. But it doesn't have that gigabit serial connector yet.
I think for c-PCI-S the clock should be placed on the gigabit connector and there should be no MMCX jumper. To do that (a) place MMCX in just above the right EEM, (b) the gigabit connector above the left EEM (or between the EEMs if that fits), (c) add jumper capacitors to switch the clock between the balun and a pair on the gigabit connector. @gkasprow does this make sense?

**Comment by gkasprow** [comment]
yes. done.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/69834796-ff5f6100-123c-11ea-886f-87c3474f7c53.png)

**Comment by gkasprow** [comment]
btw, recent CERN DI/OT board based on 500$ ZU7 SoC has also gigabit line per CPCIS slot + 15 LVDS + low jitter clock. WIth one assembly option the user can decide if one needs 16-th LVDS or gigabit link.
The project is here https://ohwr.org/project/diot/wikis/home
In a few days I will update schematics.

**Comment by gkasprow** [comment]
the Open source CPCIS backplane is already designed (in Kicad) and goes for production.
Low-cost 400W PSU is in the design phase.
