### ISSUE TITLE
upside down components on schematic

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#76]
e.g. 
![image](https://user-images.githubusercontent.com/21218399/69723688-21a89000-1112-11ea-9c12-f2b72db30d8c.png)

**Comment by gkasprow** [comment]
Please turn off the option in Altium "display strings as rotated"

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/69831261-ecdb2c80-1228-11ea-88aa-1dbb10b6e697.png)
