### ISSUE TITLE
DAC output caps on upconverting variant

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#77]
There are still rogue 10uF DC block caps in the upconverting variant (although, you did get most of them!).

**Comment by gkasprow** [comment]
which caps do you mean?

**Comment by hartytp** [comment]
IIRC there is a DC block in the DAC LPF

**Comment by jordens** [comment]
That one and everything up to the mixer/bypass needs to stay. The filter runs at the same frequencies independent of variant.

**Comment by hartytp** [comment]
Doh! Yes silly me
