### ISSUE TITLE
output transformer

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#78]
https://github.com/sinara-hw/Urukul/issues/39#issuecomment-561565760

**Comment by jordens** [comment]
This is already done. The baseband version is supposed to have that 4:1 balun. (nb I don't know whether anybody did what I asked and cross-checked that the diff filter works fine at that impedance).

**Comment by hartytp** [comment]
Okay. I suggest we leave this for now while @CannaCardo does the layout, but remember to check it before production.

**Comment by gkasprow** [comment]
@hartytp do you want us to add the power amplifier at the output?

**Comment by hartytp** [comment]
No let’s leave it as is for now

**Comment by hartytp** [comment]
@gkasprow what do you think about balun selection for phaser?

**Comment by gkasprow** [comment]
To answer your question we should make a simulation with MO or DesignerRF. Since it is a single element and it is easy to replace, we will simply do so if the performance of the existing one is not sufficient. We do not use baluns for IQ operation so their mismatch is not an issue here.

**Comment by hartytp** [comment]
It would definitely be nice to use a balun that gave a bit more output power since we're not using a pre-amp.

**Comment by hartytp** [comment]
Also, I'm not totally clear on what measurements we would want to make to verify the performance in the current arrangement.

**Comment by gkasprow** [comment]
I'd measure THD and power for interesting frequencies.

**Comment by hartytp** [comment]
ok, will do. That's easy to do and was on the list any way.

**Comment by hartytp** [comment]
Sorry, looking again at the comments above I realise that there isn't anything to do here.

The only other test I'll do is checking the power level in upconversion mode and comparing to the modulator requirements to check it's appropriate.
