### ISSUE TITLE
layout & routing review #2

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Phaser#79]
- [x] move TR5A away from J17. Baluns are very fragile and will be damaged during J17 insertion. One can move J17 down.
- [x] make R49 DNP in baseband variant
- [x] make R257 DNP in baseband variant
- [x] mark SW1A, SW1B TERM position (aka Sampler)
- [x] enable designators for RN resistive networks
- [x] mark + pin for fan connector
- [x] just above U1 there are unknown test points. Please add legend
- [x] separate RF traces as much as U can
![obraz](https://user-images.githubusercontent.com/4325054/70463097-7c4fcd80-1abc-11ea-8e11-172519fdf8fc.png)

- [x] separate traces
![obraz](https://user-images.githubusercontent.com/4325054/70463155-9b4e5f80-1abc-11ea-979c-b254f222a8ea.png)
- [x] separate ATT_CLK from neighbour traces. It is too close to LE and RST lines and will cause issues
- [x] the same with upconverter SPI CLK traces
![obraz](https://user-images.githubusercontent.com/4325054/70463321-fe3ff680-1abc-11ea-96a2-991f6356da68.png)

**Comment by gkasprow** [comment]
- [ ] the DS says that the decoupling caps should be close to the IC
![obraz](https://user-images.githubusercontent.com/4325054/70464604-845d3c80-1abf-11ea-8ecb-62647c7cf948.png) The example layout does not follow this advice strictly.
I would make the traces much thicker, try to pour polygons.
![obraz](https://user-images.githubusercontent.com/4325054/70464691-ae166380-1abf-11ea-9fa3-d0267cefdb64.png)
- [ ] make supply stubs thicker
![obraz](https://user-images.githubusercontent.com/4325054/70464897-20874380-1ac0-11ea-931c-76c347f35c92.png)
- [ ] cosmetics
![obraz](https://user-images.githubusercontent.com/4325054/70465146-9b505e80-1ac0-11ea-947d-ed4a1bf0c714.png)

**Comment by gkasprow** [comment]
- [ ] violations
![obraz](https://user-images.githubusercontent.com/4325054/70465380-1ca7f100-1ac1-11ea-8a32-132a5ffc92ce.png)
- [ ] add panel to the BOM as it is done in Fastino. Use [my libraries](https://www.dropbox.com/sh/naxdly09ulgj9bt/AAAL_bULdZhdKlPEa4TrLLyba?dl=0)

**Comment by gkasprow** [comment]
Please replace symbols and footprints with proper ones from CERNLIBs:
- [ ] LTC2323CUFD-16#TRPBF
- [ ] TRF372017IRGZT
- [ ] TPS72012DRVR
Make sure that no changes are done to PCB. This way we will make sure that in symbols created by me there are no errors.

**Comment by gkasprow** [comment]
- [ ] the IQ channels are not perfectly matched. The GND below is OK, but above the must have GND as well. Route parts of supply planes using different layers/traces. Make sure the IQ traces have GND planes above them. Use multiple vias along the lines to couple the polygons together
![obraz](https://user-images.githubusercontent.com/4325054/70467409-6abef380-1ac5-11ea-87be-f62e71c3af2e.png)

**Comment by gkasprow** [comment]
- [ ] I'm not sure if such mismatch makes any difference, but let's equalise them as well
![obraz](https://user-images.githubusercontent.com/4325054/70467579-c7baa980-1ac5-11ea-8fb2-25e747fb0b4c.png)

**Comment by hartytp** [comment]
- [ ] can we also length match between the two RF/uw outputs (not just between the I/Q of a single channel). This isn't strictly required but is always nice to do.

**Comment by hartytp** [comment]
- [ ] should the ADC sampling capacitor be as close the ADC as possible to minimize high-frequency impedance?

**Comment by hartytp** [comment]
- [ ] should IC18 be away from the AFE to avoid routing the noisy SMPS supply under the AFE?

**Comment by hartytp** [comment]
- [ ] are these traces around the power inductors thick enough? 
![image](https://user-images.githubusercontent.com/21218399/70468638-61328d00-1abf-11ea-983d-9884b22ff6d2.png)

**Comment by gkasprow** [comment]
- [ ] some components are too close to each other. Ty to follow layer 15 as clearance marker
![obraz](https://user-images.githubusercontent.com/4325054/70468467-6d224d00-1ac7-11ea-8ff4-45c20a8201a1.png). 
- [ ] @hartytp for these frequencies we don't care. It will sample it in diff way.
@hartytp IC18 gets clean 12V filtered by 4-th order LC filter. The net should be called N12V0A

**Comment by gkasprow** [comment]
>are these traces around the power inductors thick enough?

PI analysis will tell us what current density is sufficient. In case it is too high, we will make them thicker

**Comment by hartytp** [comment]
- [ ] for reliability traces should stay inside pads shouldn't they? 
![image](https://user-images.githubusercontent.com/21218399/70468778-9b039380-1abf-11ea-865a-7b9ac6b0cd9c.png)

**Comment by hartytp** [comment]
- [ ] what's the view on vias under small components? Is that ok? 
![image](https://user-images.githubusercontent.com/21218399/70468830-b373ae00-1abf-11ea-8b01-8c5b8dae1d84.png)

**Comment by gkasprow** [comment]
> for reliability traces should stay inside pads shouldn't they?

we have solder mask so it's not critical. 

>what's the view on vias under small components? Is that ok?

that's fine. we have soldermask and vias are covered

**Comment by gkasprow** [comment]
Oh, you posted wrong picture. For QFN pads yes, the tracks should stay within pads.

**Comment by hartytp** [comment]
Sorry, yes, new computer, new keyboard shortcuts...

**Comment by hartytp** [comment]
- [ ] are you happy with the isolation between the MMCX clock input and the digital traces? That looks to route right through the busiest part of the board!

**Comment by hartytp** [comment]
- [ ] what's the view on traces that bridge QFN pins like this? Does it impact soldering reliability? 
![image](https://user-images.githubusercontent.com/21218399/70469252-a0151280-1ac0-11ea-88e1-093ad8b9aa35.png)

**Comment by gkasprow** [comment]
> are you happy with the isolation between the MMCX clock input and the digital traces? That looks to route right through the busiest part of the board!

- [ ] there are only I2C lines nearby. But the clock line could be better separated from DAC LVDS lines LVDS
![obraz](https://user-images.githubusercontent.com/4325054/70469450-52e96e80-1ac9-11ea-9787-946eca5e15f1.png)

**Comment by gkasprow** [comment]
> what's the view on traces that bridge QFN pins like this? Does it impact soldering reliability?

Where did you find them? Sure, this is a serious issue because it screws the AOI

**Comment by hartytp** [comment]
- [ ] there are a few places where decoupling caps could be moved closer to the ICS to minimize inductance like here. It feels a bit odd to decouple with multiple different inductance values in parallel, but have them 5mm from the IC. That feels like a long way for a 4GHz signal
![image](https://user-images.githubusercontent.com/21218399/70469517-1580e300-1ac1-11ea-8591-549ce67d975a.png)

**Comment by gkasprow** [comment]
- [ ] Here they are
![obraz](https://user-images.githubusercontent.com/4325054/70469618-a8be1680-1ac9-11ea-8cff-0cd06ff9428c.png)

**Comment by hartytp** [comment]
> Where did you find them? Sure, this is a serious issue because it screws the AOI

Several places like IC22. Also, what's the view on traces coming out of the side of pads on QFNs? I see that in a few places (on the corner pins). It's not necessary for the layout and I didn't think it was a good idea.

**Comment by gkasprow** [comment]
> there are a few places where decoupling caps could be moved closer to the ICS to minimize inductance like here. It feels a bit odd to decouple with multiple different inductance values in parallel, but have them 5mm from the IC. That feels like a long way for a 4GHz signal

this I posted already. @CannaCardo followed strictly datasheet recommendation but I think the traces should be thicker and caps placed closer

**Comment by gkasprow** [comment]
it's not a problem if traces go from the QFP pad side.

**Comment by hartytp** [comment]
- [ ] keep a nice big clearance between mount holes and components/traces. I've had too many cases where someone picks a bolt with a larger head than the component library assumed. 
![image](https://user-images.githubusercontent.com/21218399/70469813-af489000-1ac1-11ea-92c6-4c8d5d715d6b.png)

**Comment by gkasprow** [comment]
- [ ] avoid bridges between pads
![obraz](https://user-images.githubusercontent.com/4325054/70469871-34d03e00-1aca-11ea-9836-14c5be6893c4.png)

**Comment by hartytp** [comment]
@gkasprow what do you think about the digital/analog isolation; smps (and other nosie source) layout; keeping critical sections like loop filters compact; minimizing decoupling inductances; etc?

**Comment by gkasprow** [comment]
As I wrote, I will add some slots in GND that will further improve isolation. To me, it looks that we should not have issues with them. We have 2 GND planes whith will provide low impedance for return signals.

**Comment by hartytp** [comment]
@CannaCardo over all I think it's a really good layout. Good work!

A few small points above to consider, but I don't think it's far off at all. Thanks!!

**Comment by hartytp** [comment]
@gkasprow great! I agree, I don't see any major issues with the layout.

@WeiDaZhang any thoughts?

**Comment by CannaCardo** [comment]
> Please replace symbols and footprints with proper ones from CERNLIBs:
> 
> * [x]  LTC2323CUFD-16#TRPBF
> * [x]  TRF372017IRGZT
> * [x]  TPS72012DRVR
>   Make sure that no changes are done to PCB. This way we will make sure that in symbols created by me there are no errors.

No errors found

**Comment by CannaCardo** [comment]
I've moved decoupling caps closer to IC2A / IC2B and made the traces thicker (not much space for polygons here), please confirm if that's enough. The filter components are physically large so bringing them closer would also place them near the signal path (pin 36 ext_vco)

**Comment by hartytp** [comment]
> I've moved decoupling caps closer to IC2A / IC2B and made the traces thicker (not much space for polygons here), please confirm if that's enough. The filter components are physically large so bringing them closer would also place them near the signal path (pin 36 ext_vco)

Thanks! As a general point, can you have a look over the design and try to make sure that the layout is as tight as possible (minimizing parasitic inductances/loop areas etc) for all high-frequency/low noise (including things like SMPSs) areas of the board. I'll double check once the next layout RC is complete, but you've spent much more time thinking about this than me and are a better person to judge.

**Comment by hartytp** [comment]
Thanks for the tours all! Excited to see this spooled 
![E003A609-A8AB-4384-9CDC-361B1F044845](https://user-images.githubusercontent.com/21218399/75296307-b0699d80-5824-11ea-83c7-419ab4af9235.jpeg)

**Comment by hartytp** [comment]
Did this come off the production line yet?

**Comment by gkasprow** [comment]
Yes, today.

**Comment by hartytp** [comment]
Cool! Photo? :)
