### ISSUE TITLE
layout RC7

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#80]
- [x] ADC sampling caps are still quite far from the ADC

**Comment by hartytp** [comment]
- [ ] what's the power rating on the termination resistors you used? did you copy those from sampler?

**Comment by hartytp** [comment]
Other than that I don't see any issues (although I haven't been over it in detail with Altium). Good work!

**Comment by gkasprow** [comment]
@CannaCardo I will finish the PI analysis and address @jordens issues.

**Comment by hartytp** [comment]
Wonderful! Thanks all
