### ISSUE TITLE
polygon crossings

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#81]
between MidLayer2 and SignalLayer1 (which are adjacent AFAICT)

RF BB

![image](https://user-images.githubusercontent.com/1338946/70846523-59297300-1e5a-11ea-883c-900e202cb091.png)

GT pairs

![image](https://user-images.githubusercontent.com/1338946/70846530-63e40800-1e5a-11ea-8f94-7e42545f266e.png)

DAC and GT pairs

![image](https://user-images.githubusercontent.com/1338946/70847269-e670c580-1e62-11ea-8328-187be131acea.png)

Or is the assumption that 0.73 mm is far away so that there is little coupling?

**Comment by jordens** [comment]
I would have just put all the high frequency signals (dac differential, dac baseband to switch, GT links) that don't fit on the top layer on the bottom layer and not some inner layer. that way you only need to look at one adjacent copper plane and not two. and the via stubs are also gone (but this is probably not that critical at ~4 GHz yet).

**Comment by gkasprow** [comment]
I managed to cover all DAC analog lines with GND on both sides.
I don't care that much about GTH since they are coupled mostly with the layer5. I optimized the planes to minimize Z discontinuity.

**Comment by gkasprow** [comment]
We would need to add at least one more layer to fully support GTP lines. But since we won't probably use them at all, it's not worth the effort. Moving them to the bottom layer is not that easy

**Comment by hartytp** [comment]
Great

**Comment by jordens** [comment]
Sounds good. We should just do a loopback sata and check the SI with the Bert scanner.
