### ISSUE TITLE
upconverter exposed copper

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#82]
please expose the bottom copper under the mixer for potential cooling.
and make it one continuous ground area, don't cut it up.
it doesn't need to be large, 1cm by 1cm would be fine.
no need for the large copper planes away from the upconverter imo (@gkasprow ?)

![image](https://user-images.githubusercontent.com/1338946/70846556-a4dc1c80-1e5a-11ea-9296-cb8173cfb0bc.png)

**Comment by gkasprow** [comment]
done
