### ISSUE TITLE
decide on variant names and be consistent

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#84]
either BB/UC or baseband/upconverter, but if possible not both: panel names, panel markings, pdf names, etc.

**Comment by gkasprow** [comment]
is that OK ?
![obraz](https://user-images.githubusercontent.com/4325054/70871533-43be6100-1fa0-11ea-9948-574723108211.png)
![obraz](https://user-images.githubusercontent.com/4325054/70871536-4c169c00-1fa0-11ea-8a35-b71554872289.png)

**Comment by jordens** [comment]
Yes
