### ISSUE TITLE
u.fl and SMT MMCX

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#86]
* Are you confident the SMT MMCX are mechanically robust enough? IME SMT connectors are a reliability issue (see the typical micro-USB failures), especially if there are significant insertion/extraction forces. @gkasprow 
* If you are happy with the SMT MMCX, then I'd really use them for the debug connectors as well (J4A J4B)

**Comment by gkasprow** [comment]
they need vias that attach pads to inner layers and polygon above to be robust.

**Comment by jordens** [comment]
If that works I'm happy with it.

 I thought you needed a pin or wing through the pcb together with it's solder to protect from pad shear.

**Comment by jordens** [comment]
On the other hand that pretty much kills the notion of SMT connectors not piercing through all layers. The vias may actually make the effective footprint of a SMT connector larger than the through-hole style.

**Comment by jordens** [comment]
I'll leave the u.fl and MMCX connector style choice to you then.

**Comment by gkasprow** [comment]
I changed ufl to MMCX to reduce the BOM
