### ISSUE TITLE
SMA grounding resistor

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#87]
Don't do this. DNP them all IMO.

![image](https://user-images.githubusercontent.com/1338946/70846790-57ad7a00-1e5d-11ea-901d-ed238b3e13d2.png)

There is a ground resistor on the balun shield input.

![image](https://user-images.githubusercontent.com/1338946/70846812-8166a100-1e5d-11ea-8cef-696d5d57a602.png)

**Comment by gkasprow** [comment]
It does not really matter from SI point of view but can make confusion.
