### ISSUE TITLE
upconverter refin layout

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#88]
currently alone on the bottom layer. put this on the same layer as the other high frequency signals.

![image](https://user-images.githubusercontent.com/1338946/70846880-50d33700-1e5e-11ea-86af-11ddca54f5fa.png)

for the upper channel move the balun lower, move the lm75 out of the way upwards to disentangle the routing.

![image](https://user-images.githubusercontent.com/1338946/70846901-80823f00-1e5e-11ea-9297-41407e9bd15f.png)

**Comment by gkasprow** [comment]
done
