### ISSUE TITLE
LED sizes

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#90]
Please confirm that the LED sizes are the same as on Sampler/DIO-SMA/DIO-BNC etc and not the big ones as on Urukul v1.3 (https://github.com/sinara-hw/Urukul/issues/17) and check that the panel holes are correct (small size).

**Comment by gkasprow** [comment]
LEDs are small
![obraz](https://user-images.githubusercontent.com/4325054/70865559-4056b580-1f5f-11ea-8e4a-4877d0505b66.png)
