### ISSUE TITLE
keepout clearance

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Phaser#93]
Just confirm that you are happy with these collisions between the clearances and between clearance and keeout:

![image](https://user-images.githubusercontent.com/1338946/70847434-9d217580-1e64-11ea-812b-0f15c7077fdb.png)

![image](https://user-images.githubusercontent.com/1338946/70847446-bc200780-1e64-11ea-8520-fb4e56ef36e6.png)

![image](https://user-images.githubusercontent.com/1338946/70847453-d35ef500-1e64-11ea-86f4-28ca16ee6821.png)

![image](https://user-images.githubusercontent.com/1338946/70847459-de198a00-1e64-11ea-98b5-9d1a637cd785.png)

![image](https://user-images.githubusercontent.com/1338946/70847462-eb367900-1e64-11ea-9852-d6edcba8fc21.png)

**Comment by gkasprow** [comment]
some of them are top and bottom overlapping. Some need fixing.

**Comment by gkasprow** [comment]
Some are fine, some I fixed.
