### ISSUE TITLE
IC21 Ven

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Phaser#96]
@gkasprow actually, I did spot one thing!

IC21 Ven is driven from 1V5. However the data sheet requires a min of 1.7V

![image](https://user-images.githubusercontent.com/21218399/70992249-2a610600-20c1-11ea-959e-bfc63dd35e9b.png)

**Comment by hartytp** [comment]
TPS74901RGWT is okay with 1V1 so the other supplies on this rail are fine.

![image](https://user-images.githubusercontent.com/21218399/70992312-48c70180-20c1-11ea-9e27-d15bda51716d.png)

**Comment by hartytp** [comment]
@gkasprow other than that I don't see any issues with the two regulator changes, but let me know if there is anything else I should look at.

**Comment by gkasprow** [comment]
OK, so I have to add a pullup resistor.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/70997826-28557200-20d6-11ea-87e0-4070bf0c4139.png)

**Comment by hartytp** [comment]
Thanks!
